#!/usr/bin/env python

import sys

from pyriver.api import create_app
from pyriver.builtin import (
    build,
    init,
    run
)

def load():
    pass


def pull():
    pass


def push():
    pass


def backfill():
    pass


commands = {
    "build": build.execute,
    "init": init.execute,
    "load": load,
    "run": run.execute,
    "pull": pull,
    "push": push,
    "backfill": backfill
}


if __name__ == "__main__":
    with create_app().app_context():
        commands[sys.argv[1]]()
